### PR TITLE
make torch, transformers, pysrt and spacy optional dependencies

### LINKED ISSUE #28: warning: The package `typer==0.12.5` does not have an extra named `all`
Thanks for the great package!

When I run: 

```bash
pip install video_sampler==0.11.0
```

I get this warning: 

```bash
warning: The package `typer==0.12.5` does not have an extra named `all`
```

Removing `[all]` in this line would fix that I believe:

https://github.com/LemurPwned/video-sampler/blob/72ec1bb58790a7e7d21e9e5bc07d22cd41bf0544/pyproject.toml#L34

### LINKED ISSUE #29: `torch`, `spacy`, `transformers`, `pysrt` should be optional dependencies
## 🚀 Feature Request

`torch`, `spacy`, `transformers`, `pysrt` are hard dependencies but should be optional.

When I run this import:

```python
from video_sampler.sampler import SamplerConfig, VideoSampler
```

I get this error:
```bash
Traceback (most recent call last):
  File "/home/.../test_video_sampler.py", line 1, in <module>
    from video_sampler.sampler import SamplerConfig, VideoSampler
  File "/home/.../venv/lib/python3.10/site-packages/video_sampler/__init__.py", line 6, in <module>
    from .sampler import VideoSampler, Worker
  File "/home/.../venv/lib/python3.10/site-packages/video_sampler/sampler.py", line 13, in <module>
    from .gating import create_gate
  File "/home/.../venv/lib/python3.10/site-packages/video_sampler/gating.py", line 106, in <module>
    class ClipGate:
  File "/home/.../venv/lib/python3.10/site-packages/video_sampler/gating.py", line 168, in ClipGate
    def _get_margins(self, frame_embeds: torch.Tensor):
NameError: name 'torch' is not defined
```

This line is the source of the error:

https://github.com/LemurPwned/video-sampler/blob/72ec1bb58790a7e7d21e9e5bc07d22cd41bf0544/video_sampler/gating.py#L168

## 🔈 Motivation

I am not interested in the clip gating and visualization feature, I only want to sample frames from a video using classical methods. In this case, I shouldn't need `torch` (huge dependency) or `transformers` packages installed in the env to sample frames from a video.

It can be an optional dependency only triggered when the user calls the `ClipGate` class or `build_feature_model`, `parse_srt_subtitle`, `build_feature_model` functions.

## Pull Request

Opened a pull request for this: https://github.com/LemurPwned/video-sampler/pull/30

### PR DESCRIPTION
**Pull request by fcakyon**
fixes https://github.com/LemurPwned/video-sampler/issues/29
cc: @LemurPwned

## Summary by Sourcery

Make torch, transformers, pysrt and spacy optional dependencies by moving their imports inside the functions that require them, reducing the need for these packages unless their specific functionality is used.

Enhancements:
- Make torch, transformers, pysrt and spacy optional dependencies by importing them within functions where they are used.

### CODE REVIEW

**Comment by LemurPwned** [comment]
Thanks a lot @fcakyon. 
I'll use this PR to bump the version and add missing base requirements as well

**Comment by LemurPwned** [comment]
@sourcery-ai review

**Comment by LemurPwned** [comment]
Thanks again @fcakyon for your contribution!

**Comment by fcakyon** [comment]
@LemurPwned thanks for your fast response 🙏🏻

**Pull request merged**
